// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrc1UJ4TLhRX5mfpzkFU31zYI3UEfQh38',
    appId: '1:879266768055:web:fc2067013b2e0853b49932',
    messagingSenderId: '879266768055',
    projectId: 'flutter--app-5d1ba',
    authDomain: 'flutter--app-5d1ba.firebaseapp.com',
    storageBucket: 'flutter--app-5d1ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxPwqn--135jYmIbSc-8RAq2bSYGVn5kY',
    appId: '1:879266768055:android:fa3da19346c793c6b49932',
    messagingSenderId: '879266768055',
    projectId: 'flutter--app-5d1ba',
    storageBucket: 'flutter--app-5d1ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2YC5xH9z5nbe03petYMx-9FoF2RoGhjs',
    appId: '1:879266768055:ios:9522c2dcdae7d0d5b49932',
    messagingSenderId: '879266768055',
    projectId: 'flutter--app-5d1ba',
    storageBucket: 'flutter--app-5d1ba.appspot.com',
    iosBundleId: 'com.example.simpleProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2YC5xH9z5nbe03petYMx-9FoF2RoGhjs',
    appId: '1:879266768055:ios:b7a3895533d0a3ddb49932',
    messagingSenderId: '879266768055',
    projectId: 'flutter--app-5d1ba',
    storageBucket: 'flutter--app-5d1ba.appspot.com',
    iosBundleId: 'com.example.simpleProject.RunnerTests',
  );
}
